### ISSUE TITLE
Tag the current commit as a release

### ISSUE THREAD

**Issue by bjornpost** [gridonic/hapi#10]
Hi,

Hoping that you will merge my changes; I think it's a good idea to tag the current commit as release `0.1` (or something), so we can release `1.0` as a release that has a breaking API (SSL forced, public functions/classes renamed).

Moving from `0.1` to `1.0` maybe sounds a bit steep, but following semver this is needed as the changes aren't backward compatible:

> Major version X (X.y.z | X > 0) MUST be incremented if any backwards incompatible changes are introduced to the public API. It MAY include minor and patch level changes. Patch and minor version MUST be reset to 0 when major version is incremented.

**Comment by peschee** [comment]
Done.
