### ISSUE TITLE
Is this API missing a GetProjectActiveTasks?

### ISSUE THREAD

**Issue by mledwards** [gridonic/hapi#22]
I can't for the life of me work out how to do it, but I feel like it should be here somewhere or it's pretty difficult to work out project_id / task_id combinations for creating new entries.

**Comment by creativeorange** [comment]
Is there any progress in fixing this issue?

**Comment by peschee** [comment]
@jfierz Could you have a look?

**Comment by mledwards** [comment]
Basically I've used the getClientActiveProjects method which saved me a lot of work, but then got stuck trying find getProjectActiveTasks.

Thank you for taking a look, it's much appreciated.

**Comment by jfierz** [comment]
@mledwards You can now use the getProjectTasks method for that, but note that if you only need the task_id's instead of the full Task objects, you can also use the getProjectTaskAssignments method. This will return an array of TaskAssignments which contain the task_id and is much more efficient.

**Comment by mledwards** [comment]
Thanks @jfierz!

The code in the getProjectTasks function is the work around I used :)
